### PR TITLE
Corrected the NVDLA driver to work with 5.13

### PR DESCRIPTION
**Pull request by cybergaszcz**
Corrected changes in API for the NVDLA driver to work with upstream kernel. Below results of tests:

```
./nvdla_runtime --loadable fast-math.nvdla --image 0_3.jpg --rawdump
creating new runtime context...
Emulator starting
dlaimg height: 28 x 28 x 1: LS: 128 SS: 0 Size: 3584
Enter:dla_read_network_config
(DLA_TEST) Error 0x00000004: Mismatched channel: 1 != 4 (in TestExit:dla_read_network_config status=0
Utils.cpp, function createImageCopy(), line 160)
submitting tasEnter: dla_initiate_processors
ks...
...
reset engine done
Work Found!
Work Done
execution time = 1797976.000000 s
Shutdown signal received, exiting
Test pass
[riscv@fedora-starfive ~]$ ./nvdla_runtime --loadable fast-math.nvdla 
[riscv@fedora-starfive ~]$ cat output.dimg 
0 0 0 117 0 2 0 0 0 0

./nvdla_runtime --loadable fast-math.nvdla --image 0_3.jpg --rawdump
creating new runtime context...
Emulator starting
dlaimg height: 28 x 28 x 1: LS: 128 SS: 0 Size: 3584Enter:dla_read_network_config

(DLA_TEST) Error 0x00000004: Mismatched channel: 1 != 4 (in TeExit:dla_read_network_config status=0
stUtils.cpp, function createImageCopy(), line 160)
submitting tEnter: dla_initiate_processors
asks
...
reset engine done
Work Found!
Work Done
execution time = 1794760.000000 s
Shutdown signal received, exiting
Test pass
[riscv@fedora-starfive ~]$ ls
0_3.jpg  fast-math.nvdla        libjpeg.a      output.dimg
0_7.jpg  fast-math-small.nvdla  nvdla_runtime
[riscv@fedora-starfive ~]$ cat output.dimg 
0 0 0 0 0 0 0 119 0 0
```

### CODE REVIEW

**Comment by esmil** [comment]
Nice! I can't merge this as-is though as it contains merges of a lot of unrelated commits and that won't work when rebasing the beaglev branch on the next rc. Could you try if this for you:
https://github.com/esmil/linux/tree/beaglev-nvdla

**Comment by cybergaszcz** [comment]
> Could you try if this for you:
> https://github.com/esmil/linux/tree/beaglev-nvdla
Ok, this branch contains all these changes related to the NVDLA. I am closing this pull request.

**Comment by esmil** [comment]
@cybergaszcz So did you try building that branch and running it?

**Comment by cybergaszcz** [comment]
Yes, I have tested it and works properly. Thank you for support.

```
[riscv@fedora-starfive ~]$ uname -a
Linux fedora-starfive 5.13.0-rc7-beaglev-308898-g56b4d6160381 #1 SMP Mon Jun 21 15:58:06 CEST 2021 riscv64 riscv64 riscv64 GNU/Linux
[riscv@fedora-starfive ~]$ dmesg | grep nvdla
[    1.444778] NVDLA 11940000.nvdla: coherent device 0 dev->dma_coherent 0
[    1.453576] Probe NVDLA config nvidia,nvdla_os_initial
[    1.471860] [drm] Initialized nvdla 0.0.0 20171017 for 11940000.nvdla on minor 0
[    1.480906] NVDLA 11940000.nvdla: Get mem from memory-region

./nvdla_runtime --loadable fast-math.nvdla  --image0_7.jpg --rawdump
creating new runtime context...
Emulator starting
dlaimg height: 28 x 28 x 1: LS: 128 SS: 0 Size: 3584Enter:dla_read_network_config

(DLA_TEST) Error 0x00000004: Mismatched channel: 1 != 4 (in TeExit:dla_read_network_config status=0
stUtils.cpp, function createImageCopy(), line 160)
submitting tEnter: dla_initiate_processors
asks...
...
reset engine done
Work Found!
Work Done
execution time = 1799008.000000 s
Shutdown signal received, exiting
Test pass                                                                                                  cat output.dimg 
0 0 0 0 0 0 0 119 0 0 [riscv@fedora-starfive ~]$ 

[riscv@fedora-starfive ~]$ cat /proc/interrupts 
           CPU0       CPU1       
  5:      11941       9474  RISC-V INTC   5  riscv-timer
  7:        850          0  SiFive PLIC  73  ttyS0
  8:          0          0  SiFive PLIC   2  dw_axi_dmac_platform
 10:          0          0  SiFive PLIC   1  dw_axi_dmac_platform
 11:         85          0  SiFive PLIC  44  xhci-hcd:usb1
 13:          0          0  SiFive PLIC  43  104c0000.usb
 14:          0          0  SiFive PLIC  32  11910000.gpio
 15:        253          0  SiFive PLIC  96  118b0000.i2c
 16:          0          0  SiFive PLIC  97  118c0000.i2c
 17:          0          0  SiFive PLIC  74  12450000.i2c
 18:          7          0  SiFive PLIC  98  118d0000.trng
 20:          0          0  SiFive PLIC   6  eth0
 21:          0          0  SiFive PLIC   7  eth0
 22:         12          0  SiFive PLIC  22  11940000.nvdla
 26:          0          0  SiFive PLIC  70  12410000.spi
 29:      24024          0  SiFive PLIC   4  dw-mci
 30:       7234          0  SiFive PLIC   5  dw-mci
 31:       3698          0  SiFive PLIC 101  sf_lcdc
 32:          0          0  SiFive PLIC 103  sf_vpp1
 35:         10          0  SiFive PLIC 122  124a0000.tmon
IPI0:        92        105  Rescheduling interrupts
IPI1:      2528      12933  Function call interrupts
IPI2:         0          0  CPU stop interrupts
IPI3:         0          0  IRQ work interrupts
IPI4:         0          0  Timer broadcast interrupts
```

**Comment by esmil** [comment]
Thanks. I'll push this to the beaglev branch then.

**Comment by esmil** [comment]
@cybergaszcz Hey, I just noticed this driver includes code to flush caches. This should be obsoleted by Atish' generic non-coherent dma solution that is on the beaglev branch. Could you try if something like this still works for you on the beaglev branch: http://sprunge.us/rBNdHk

**Comment by cybergaszcz** [comment]
Hey,
Thanks. Yes, I have checked and everything works fine:

```
[riscv@fedora-starfive ~]$ uname -a
Linux fedora-starfive 5.13.0-rc7-beaglev-308899-gc7f42bb10e72 #2 SMP Thu Jun 24 07:06:52 CEST 2021 riscv64 riscv64 riscv64 GNU/Linux
[riscv@fedora-starfive ~]$ dmesg | grep nvdla
[    1.448746] NVDLA 11940000.nvdla: coherent device 0 dev->dma_coherent 0
[    1.457482] Probe NVDLA config nvidia,nvdla_os_initial
[    1.475764] [drm] Initialized nvdla 0.0.0 20171017 for 11940000.nvdla on minor 0
[    1.484817] NVDLA 11940000.nvdla: Get mem from memory-region
Work Found!
Work Done
execution time = 1794150.000000 s
Shutdown signal received, exiting
Test pass
[riscv@fedora-starfive ~]$ ls
0_3.jpg  fast-math.nvdla        libjpeg.a      output.dimg
0_7.jpg  fast-math-small.nvdla  nvdla_runtime
[riscv@fedora-starfive ~]$ cat output.dimg 
0 0 0 0 0 0 0 119 0 0 [riscv@fedora-starfive ~]$ cat /proc/interrupts 
           CPU0       CPU1       
  5:      13756      10262  RISC-V INTC   5  riscv-timer
  7:        928          0  SiFive PLIC  73  ttyS0
  8:          0          0  SiFive PLIC   2  dw_axi_dmac_platform
 10:          0          0  SiFive PLIC   1  dw_axi_dmac_platform
 11:         86          0  SiFive PLIC  44  xhci-hcd:usb1
 13:          0          0  SiFive PLIC  43  104c0000.usb
 14:          0          0  SiFive PLIC  32  11910000.gpio
 15:        254          0  SiFive PLIC  96  118b0000.i2c
 16:          0          0  SiFive PLIC  97  118c0000.i2c
 17:          0          0  SiFive PLIC  74  12450000.i2c
 18:          7          0  SiFive PLIC  98  118d0000.trng
 20:          0          0  SiFive PLIC   6  eth0
 21:          0          0  SiFive PLIC   7  eth0
 22:         12          0  SiFive PLIC  22  11940000.nvdla
 26:          0          0  SiFive PLIC  70  12410000.spi
 29:      31016          0  SiFive PLIC   4  dw-mci
 30:       7309          0  SiFive PLIC   5  dw-mci
 31:       5731          0  SiFive PLIC 101  sf_lcdc
 32:          0          0  SiFive PLIC 103  sf_vpp1
 35:         16          0  SiFive PLIC 122  124a0000.tmon
IPI0:        90        113  Rescheduling interrupts
IPI1:      3104      17331  Function call interrupts
IPI2:         0          0  CPU stop interrupts
IPI3:         0          0  IRQ work interrupts
IPI4:         0          0  Timer broadcast interrupts
```

**Comment by esmil** [comment]
Thanks! I'll push that patch to beaglev then.

**Comment by geertu** [comment]
Note that this driver is using dma_declare_coherent_memory(), which is planned to be removed by Christoph.
https://lore.kernel.org/linux-sh/20210623133205.GA28589@lst.de/

**Comment by cybergaszcz** [comment]
> Note that this driver is using dma_declare_coherent_memory(), which is planned to be removed by Christoph.
> https://lore.kernel.org/linux-sh/20210623133205.GA28589@lst.de/

In final version of the BeagleV there will be no NVDLA. I have adapted it only to test present HW on beta version of the BeagleV.

**Comment by pdp7** [comment]
@cybergaszcz We have not communicated this to the public yet, but there will be more JH7100 SoC's produced as a ~3,000 run.  It won't be full mass production wafer run like the JH7110 will be, but it does mean your efforts for NVDLA on the JH7100 will have a benefit beyond just those in the beta developer program.

**Pull request closed without merging**
