### PR TITLE
CONFIG_MICREL_PHY=y

### PR DESCRIPTION
**Pull request by xypron**
The micrel module is required for Ethernet. Let's build it into the kernel.

Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

### CODE REVIEW

**Comment by pdp7** [comment]
@tekkamanninja please test this as you told me yesterday you had trouble when it was built-in with your Fedora 5.10 kernel.  This does appear to fix the problem and work well on @esmil 5.12 starlight branch.

**Comment by xypron** [comment]
What one really has to know is that you first have to install the the kernel with `rpm --reinstall <foo.rpm>` and than call `dracut -fv --kver <kernel_version>`. Quite different to Debian packages that automatically call update-initramfs. And then you still have to get the new kernel into /boot/extlinux/extlinux.conf due to the messed up u-boot.

**Comment by pdp7** [comment]
@xypron what defconfig did you use to compile the kernel you tested with?

**Comment by xypron** [comment]
@pdp7: I used the defconfig that the patch updates:  `make starfive_vic7100_evb_sd_net_fedora_defconfig`

**Comment by pdp7** [comment]
@xypron thank you

**Pull request merged**
