### PR TITLE
add minimal known-working defconfig from SDK

### PR DESCRIPTION
**Pull request by sarnold**
This provides a known-good defconfig target for meta-riscv, the riscv64-multiplatform builder, etc.

### CODE REVIEW

**Comment by pdp7** [comment]
@esmil @geertu @tekkamanninja what do you think of this defconfig?  It originates from https://github.com/starfive-tech/freelight-u-sdk/blob/starfive/conf/sdk_210209_defconfig

**Comment by esmil** [comment]
Which kernel tree is this for? It has some options for the bcmdhd driver that I've removed for my starlight branch since the upsteam brcmfmac driver seems to work.

Compared to the starlght_defconfig I've added to my branch this adds some deprecated options:
CONFIG_SERIAL_EARLYCON_RISCV_SBI=y
CONFIG_AUTOFS4_FS=y

Some drivers for hardware that's not on the board. eg.:
CONFIG_MMC_SPI=y
CONFIG_SPI_SIFIVE=y
CONFIG_RTC_DRV_GOLDFISH=y
CONFIG_POWER_RESET_SYSCON=y

And leaves out options for reboot to work and the LED that Geert added:
CONFIG_POWER_RESET_TPS65086=y
CONFIG_LEDS_TRIGGER_HEARTBEAT=y

EDIT: Oh, sorry. I see now this is against the 5.10 tree without the cleaned up devicetree Then the bcmdhd options are fine and the two options above don't make any difference.

**Comment by mcd500** [comment]
I already have done making arch/riscv/configs/defconfig for upstreaming here https://github.com/esmil/linux/pull/6 which was originated from https://github.com/esmil/linux/pull/2.

**Comment by mcd500** [comment]
@tekkamanninja @pdp7 @geertu @esmil Should I make a PR at https://github.com/starfive-tech/linux/ for the https://github.com/esmil/linux/pull/6 after the h7100-upstreaming branch is created?

**Comment by sarnold** [comment]
Kinda seems like 5.10 is (mostly) bypassed already, so you should probably close this.

**Pull request closed without merging**
